### ISSUE TITLE
not work in sketch 39.1

### ISSUE THREAD

**Issue by rumeee** [wuwa/sketch-copy-to-all#2]
Thank you offered this plugin.
when I used this in sketch 39.1, the layer only copy+rename *:c2all in selected airborad, others not copy.
So,is this plugin didn't support sketch 39.1 ?

**Comment by wuwa** [comment]
i will have to check this, not tested yet on the new sketch version

**Comment by wuwa** [comment]
fixed support for sketch 39.1
