### ISSUE TITLE
Layer name gets appended when plugin runs

### ISSUE THREAD

**Issue by irabronson** [wuwa/sketch-copy-to-all#3]
Hello,

Would you be able to not have the plugin append ":c2all" to each duplicated layer? 

I'm using Sketch 42 (36781) on Mac 10.12.2.

Thanks.

**Comment by wuwa** [comment]
that's not an issue, it's the way it works to retain the connection between the master and duplication.

**Comment by irabronson** [comment]
While that is not an "Issue" with regard to the "Issues" tab here, it IS an issue for layers and prototyping, like in Principle for example. Layers in different artboards need the same name so they automatically animate. 

With the appended name, there's now the extra task of having to rename layers, because now in the destination artboard the animation can either not work or the layer can disappear.
